---
# defaults file for win_ad_install
deployment_guid: 2f19

ad_domain_name: ad1.{{deployment_guid}}.example.opentlc.com

ad_safe_mode_password: "{{ansible_password}}"

ad_admin_user: "admin@{{ad_domain_name}}"

ad_admin_password: "{{ansible_password}}"