---
# tasks file for win_service_config
- name: Configure Windows Server
  block:
    - name: Installs Package
      win_chocolatey:
        name: "{{ package_name }}"
        state: present
        package_params: "{{ parameters }}"

    - name: Enables Service
      win_service:
        name: "{{ service_name }}"
        state: started
    
    - name: Allows Ingress Traffic
      win_firewall_rule:
        name: "{{ service_name }}"
        localport: "{{ local_port }}"
        action: allow
        direction: in
        protocol: "{{ protocol_name }}"
        state: present
        enabled: yes